### PR TITLE
Update to v1.7.1

### PR DESCRIPTION
**Pull request by Starefossen**
This PR updates the installed io.js version in all Dockerfiles to v1.7.1.

Related: iojs/io.js#1396

### CODE REVIEW

**Comment by devinus** [comment]
:+1:

**Comment by subfuzion** [comment]
Please merge! :+1:

**Comment by Starefossen** [comment]
Merged!

**Comment by lo1tuma** [comment]
Seems like this version wasn’t pushed to the registry.

**Comment by Starefossen** [comment]
@lo1tuma since iojs is an official Docker image, this needs to go through the official Docker image repository as well. I have opened docker-library/official-images#664.

**Comment by lo1tuma** [comment]
Ah thanks, didn't know that.

**Comment by subfuzion** [comment]
Thanks, @Starefossen

**Comment by pesho** [comment]
Thanks @Starefossen :+1:

**Comment by Starefossen** [comment]
Just a heads up that the new version was merged into the official Docker library some days ago. The new tags are pullable even though they are not listed on the [registry website](https://registry.hub.docker.com/_/iojs/tags/manage/). The Docker guys are [aware of the issue](https://github.com/docker-library/official-images/pull/664#issuecomment-94532867), and I believe they are working on a fix.

**Pull request merged**
