### PR TITLE
Nominating Christopher Horrell @chorrell to the Docker WG

### PR DESCRIPTION
**Pull request by Starefossen**
In #58 @pesho brought up that Christopher should be invited to the Docker Working Group, and I could not agree more! I reached out to Christopher, and [he replied positively](https://twitter.com/chorrell/status/600031685477011457) when I asked if he would like to join the Docker Working Group.

For those who do not know Christopher, he works as Solutions Engineering Manager at Joyent and has been maintaining the official [`node` Docker image](https://registry.hub.docker.com/_/node/) @ [joyent/docker-node](https://joyent/docker-node/). Christopher has a lot of experience with maintaining and testing container images and I believe he will be a valuable addition to the Working Group.

### CODE REVIEW

**Comment by pesho** [comment]
:+1:

**Comment by hmalphettes** [comment]
+1

**Comment by Starefossen** [comment]
Ping @jlmitch5 and @wblankenship

**Comment by jlmitch5** [comment]
sounds good!  :)

**Comment by Starefossen** [comment]
According to the governance bylaws we need a unanimous consensus for adding new members to the working group. Ping @wblankenship

**Comment by mikeal** [comment]
The governance doc is a copy of an earlier version of the core governance document. You should probably take the latest one (which does not require unanimous consent) because the unanimous consensus thing is super annoying and unnecessary. Also, in a consensus seeking system even if you require "unanimous consent" that could be interpreted to mean that if anyone objects it doesn't pass but by no means should you require every single person to vote in the affirmative, that's just process for the sake of process and should be avoided if possible.

**Comment by Starefossen** [comment]
I agree with @mikeal. I think everyone in the WG have had plenty of time to voice their opinion on this issue. I will merge this by the end of today unless anyone disagrees.

I will PR an updated governance doc with the current core governance policy.

**Comment by pesho** [comment]
> I will PR an updated governance doc with the current core governance policy.

Thanks for that!

> I agree with @mikeal. I think everyone in the WG have had plenty of time to voice their opinion on this issue. I will merge this by the end of today unless anyone disagrees.

While I agree in general, merging this now is technically a violation of our current governance policy. As there is no rush, it would be better to first update the policy, and then do the merge (unless @wblankenship votes as well, of course).

**Comment by mikeal** [comment]
> While I agree in general, merging this now is technically a violation of our current governance policy.

That depends on how you interpret the rule. The default rule for decision making is consensus seeking with a majority vote if a consensus cannot be reached. This old amendment to that rule doesn't clearly state whether it's amending the entire consensus seeking process or just the majority vote when a consensus cannot be reached. I would interpret this as the latter and continue to use lazy consensus seeking without unanimous affirmative approval and just treat any dissent as a lack of unanimity.

BTW, this is one of the few parts of the governance document I didn't write so I can't speak to the original intention. I actually consider the entire provision a bad idea which is why I proposed, and the TSC approved, removing it from the TSC governance.

**Comment by retrohacker** [comment]
Sorry everyone.

:+1: to Christopher

:+1: to updating the governance doc as well

**Comment by Starefossen** [comment]
We have reached consensus- merging. Welcome to the Working Group @chorrell!

**Comment by pesho** [comment]
@chorrell should also be added to the @nodejs/docker team. @mikeal, can you do that?

**Comment by chorrell** [comment]
:smiley:

**Comment by tianon** [comment]
Heh, I was a little bit concerned that this whole thread had gone 100%
without Christopher chiming in; glad to see he's on board, too. :+1:

**Comment by chorrell** [comment]
Yep!

**Pull request merged**
