### PR TITLE
Prepare for image becoming official (change links, image id, etc.)

### PR DESCRIPTION
**Pull request by retrohacker**
Fixing preemptive merge from #7

### CODE REVIEW

**Comment by retrohacker** [comment]
Is it safe to merge this now that https://github.com/docker-library/official-images/pull/409 is closed and https://registry.hub.docker.com/_/iojs/ is live? Or would we like to let https://github.com/iojs/docker-iojs/issues/9 play out first?

**Comment by pesho** [comment]
I think we should wait for https://github.com/docker-library/docs/pull/141 to be merged as well. /cc @tianon @yosifkit 

#9 can wait IMO, let's gather more opinions and not rush it.

**Comment by tianon** [comment]
Since this isn't about the docs and is the source of the image itself,
wouldn't it make sense to merge this now?  You've officially got /_/iojs,
and now we're just working on the docs which are out-of-band, so I'm not
sure there's a reason to hold this up based on the docs PR, right?

**Comment by pesho** [comment]
Ok, merged.

**Pull request merged**
