### PR TITLE
Import GPG signing key for @cjihrig

### PR DESCRIPTION
**Pull request by Starefossen**
This PR adds @cjihrig GPG key to the list of keys being imported before verifying io.js binary signatures.  

Related: nodejs/io.js#2217
Signed-off-by: Hans Kristian Flaatten hans.kristian.flaatten@turistforeningen.no

### CODE REVIEW

**Comment by hmalphettes** [comment]
@Starefossen @cjihrig The upgrade from 2.4 to 2.5 broke this PR.
Let me redo this.

**Comment by hmalphettes** [comment]
Fixed here: https://github.com/nodejs/docker-iojs/commit/0a5fc1175cdb1704b172c72f3d34d53f8310da31

**Comment by Starefossen** [comment]
Thanks @hmalphettes 👍🏼

**Comment by hmalphettes** [comment]
@Starefossen enjoy the summit in SF and salutations to everyone!

**Comment by Starefossen** [comment]
Thanks, I'm really looking forward to it :smile:

**Pull request closed without merging**
