### PR TITLE
Fix GPG key retrieval and apply resilient key retrieval to slim Dockerfiles

### PR DESCRIPTION
**Pull request by jbhannah**
Docker Machine gave me the following when trying to build from the Dockerfiles with resilient GPG key retrieval added in #87:

```
/bin/sh: 1: Syntax error: end of file unexpected (expecting "done")
The command '/bin/sh -c set -ex   && for key in     9554F04D7259F04124DE6B476D5A82AC7E37093B     94AE36675C464D64BAFA68DD7434390BDBE9B9C5     0034A06D9D9B0064CE8ADF6BF1747F4AD2306D93     FD3A5288F042B6850C66B31F09FE44734EB7990E     71DCFD284A79C3B38668286BC97EC7A07EDE3FC1     DD8F2338BAE7501E3DD5AC78C273792F7D83545D   ; do     gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"   done' returned a non-zero code: 2
```

Fixed by adding a semicolon before `done`, and also applied resilient key retrieval to the slim Dockerfiles.

### CODE REVIEW

**Comment by Starefossen** [comment]
@hmalphettes any chance we can get this in before the PR to the official registry is merged?

**Comment by hmalphettes** [comment]
Done in iojs: https://github.com/nodejs/docker-iojs/commit/54780958c85a399f6516a90d128cc49fc0ad96f8

**Comment by hmalphettes** [comment]
Added to the official-images PR: https://github.com/docker-library/official-images/pull/1029
Let me know if I missed something.

**Comment by bolderbrooklyn** [comment]
:+1:, LGTM. Thanks!

**Pull request closed without merging**
