### PR TITLE
Update to v1.1.0

### PR DESCRIPTION
**Pull request by pesho**
New branch directory 1.1 added. Also added @chrisdickinson's gpg key.

### CODE REVIEW

**Comment by pesho** [comment]
Seeking +1s before merging this, as it's not completely trivial. /cc @rvagg @wblankenship

**Comment by rvagg** [comment]
I would rather leave this to @wblankenship and @ghostbar to review as the other Docker experts

**Comment by retrohacker** [comment]
lgtm :+1:

Would it be worthwhile generating these Dockefiles moving forward? `diff 1.1/Dockerfile 1.0/Dockerfile` shows that there are only two lines that change between the version bump: `gpg` and `ENV IOJS_VERSION`. With iojs using symver, maintaining these by hand may become unsustainable pretty quickly.

**Comment by pesho** [comment]
> With iojs using symver, maintaining these by hand may become unsustainable pretty quickly.

It's not by hand, the `update.sh` script helps with that. I've written some docs [here in the wiki](https://github.com/iojs/docker-iojs/wiki/Updating-versions).

I thought maintaining old branches for some time is useful, but I'm not completely sure. It would only make sense if io.js upstream is also committed to supporting old branches for some time at least with security fixes.

**Comment by retrohacker** [comment]
Would like @rvagg's thoughts on maintaining old versions.

`update.sh` looks like it only handles updates within the same major.minor change. I guess you can

```
cp -r 1.1 1.2
./update 1.2
```

lgtm

**Comment by pesho** [comment]
> It would only make sense if io.js upstream is also committed to supporting old branches for some time at least with security fixes.

In other words: Now that 1.1.0 has been released, is it 100% certain that there will never be an 1.0.5 release? /cc @rvagg @chrisdickinson

**Comment by pesho** [comment]
Anyways, let's not delay the new version image. Merging this as it is. If we decide that keeping old branches around is useless, we can delete them later.

**Comment by pesho** [comment]
Docker library PR: https://github.com/docker-library/official-images/pull/455

**Comment by retrohacker** [comment]
<:heart:>
Great work @pesho 
</:heart:>

**Comment by rvagg** [comment]
> In other words: Now that 1.1.0 has been released, is it 100% certain that there will never be an 1.0.5 release?

yes, for this one, but going forward we'll be tagging LTS releases, (or even STS!) where we'll want to increment patch version for fixes in an older release while iterating on future releases. The release strategy isn't pinned down yet but there will certainly be a lot more complexity than there is right now.

I think that for now it's safe for you to just work on the _latest_ release and let old versions disappear but as we move to a more stable state (i.e. beyond Chrome 41 when V8 4.1 becomes "stable" and therefore io.js does too) there will likely be very broad adoption and people will want to pin to specific versions (for various reasons, including reasons we don't think are good reasons). We're seeing this call for the .deb and .rpm distros from NodeSource and I think we can anticipate it here too as adoption spreads.

**Pull request merged**
