### PR TITLE
Upgrade to 1.4.3

### PR DESCRIPTION
**Pull request by hmalphettes**
It looks so trivial: let me know if I missed something.

### CODE REVIEW

**Comment by Starefossen** [comment]
LGTM

**Comment by Starefossen** [comment]
@hmalphettes This should maybe be documented better, but when this is merged someone must create a PR to the [official docker image registry for io.js](https://github.com/docker-library/official-images/blob/master/library/iojs) in order for this to be available on the Docker Hub.

**Comment by pesho** [comment]
LGTM, thanks @hmalphettes. I held off on this, because the changes in 1.4.2 and 1.4.3 are Windows-specific (don't matter in Docker), plus an NPM upgrade (which only matters in interactive usage).

**Comment by pesho** [comment]
@Starefossen it is documented here, in the wiki: https://github.com/iojs/docker-iojs/wiki/Updating-versions

@hmalphettes can you please also send the PR which @Starefossen mentioned (step 5 from the instructions in the wiki)

**Comment by Starefossen** [comment]
Maybe hold of that PR to the official docker image until 1.5 has shipped?!

 Ref. iojs/io.js#1060

**Comment by hmalphettes** [comment]
@pesho @Starefossen thanks for kindly pointing to the documentation.
I'll try this with 1.5 that has just shipped.

**Comment by pesho** [comment]
@hmalphettes already done - https://github.com/iojs/docker-iojs/pull/35 :) (but I don't think the Docker folks will merge the Hub PR before Monday)

**Comment by hmalphettes** [comment]
@pesho cheers!

**Pull request merged**
