### PR TITLE
Version bump to 2.3.3

### LINKED ISSUE #75: Request for iojs-2.3.3 Dockerfile
iojs-2.3.3 is available now with high security bug fix, https://medium.com/@iojs/important-security-upgrades-for-node-js-and-io-js-8ac14ece5852

### PR DESCRIPTION
**Pull request by retrohacker**
Critical security patch. Closes #75

### CODE REVIEW

**Comment by retrohacker** [comment]
Running tests before merge. Standby.

**Comment by retrohacker** [comment]
Smoke tested with

```
git clone https://github.com/npm/npm.git
cd npm
npm install
npm test
```

It ended with 16 of the 2334 tests failing. However 2.3.0 failed 21 of 2334 the tests as well.

```
git clone -b 2.x https://github.com/npm/npm.git
cd npm
npm install
npm test
```

It ended with16 of the 2320 tests failing. However 2.3.0 failed 16 of the 2320 tests.

Working on formalizing a CI server that automates smoke testing on more than just npm, should have done soon. Then we can start putting together a list of tests and work towards 100% pass rate.

Going ahead and merging.

:heart:

**Comment by retrohacker** [comment]
Just saw the `do not merge` label. @Starefossen, context?

**Comment by Starefossen** [comment]
Sorry, just a heads up to other collaborators that tests were pending. Ref. your comment :)

**Comment by retrohacker** [comment]
:smile: thanks!

As an aside, I've never actually merged into the official docker repo. Going to give it a go but would appreciate an extra set of eyes!

**Comment by pesho** [comment]
LGTM @wblankenship, go ahead :)

**Comment by Starefossen** [comment]
Sure thing @wblankenship. @pesho's latest PR to the Docker Registry is still pending docker-library/official-images#864

**Comment by pesho** [comment]
> Sure thing @wblankenship. @pesho's latest PR to the Docker Registry is still pending docker-library/official-images#864 - should be closed in favour of an updated PR.

Just got home, I'm ready to update that PR (as soon as this one gets merged)

edit: nevermind, will close my PR in favor of @wblankenship's

**Comment by retrohacker** [comment]
Ah! Was creating the pull request when you posted that. I need to get better notifications setup for GitHub to solve these race conditions!

**Pull request merged**
