### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### iojs/docker-iojs now has a Chat Room on Gitter

@wblankenship has just created a chat room. You can visit it here: [https://gitter.im/iojs/docker-iojs](https://gitter.im/iojs/docker-iojs?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/iojs/docker-iojs?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by Starefossen** [comment]
:+1:

**Comment by retrohacker** [comment]
Unsure about this. Thoughts @pesho? We have been doing really well keeping conversations on PRs and issues.

As an aside, I "joined" this chat not knowing it wasn't already a room. It auto-created it.

**Comment by pesho** [comment]
@wblankenship I agree that conversations on PRs and issues are working well. No objections regarding Gitter, but it will be somewhat useless if no one is there to answer questions, and putting a badge will give that impression.

**Comment by retrohacker** [comment]
Closing for now.

**Pull request closed without merging**
